### ISSUE TITLE
[tracker] Schema

### ISSUE THREAD

**Issue by at15** [at15/go-solr#9]
I think we don't need to modify field type for now, just field is enough

- [ ] list of default field types in manged schema
- [x] add field
- [ ] update field
- [x] remove field
- [ ] update unique field https://stackoverflow.com/questions/30851331/solr-5-1-0-how-to-set-the-unique-key-via-schema-api (seems impossible)
- [ ] what is the `_text_` where all fields are copied to doing?
- [ ] the error response is using 200 for status code and a different response format ....
